server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;
    index index.php index.html;



    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log warn;

    location = /healthz {
        add_header Content-Type text/plain;
        return 200 "ok\n";
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        set $php_fpm_upstream 10.89.0.1:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_pass $php_fpm_upstream;
        fastcgi_read_timeout 60s;
    }

    location ~ /\. {
        deny all;
    }
}
